### ISSUE TITLE
JOSE que harias tu 

### ISSUE THREAD

**Issue by EberMartinez1637602** [EberMartinez1637602/Percepcion-N6-Equipo-15#3]
Que consejo le darias a waluigi para que no se matara? :c

![waluigi sad](https://user-images.githubusercontent.com/42399873/44316999-7c721880-a3f4-11e8-8702-adaf797c7b01.jpeg)
que vaya por unas kawazakis, digo, que vaya a ejercitarse para no pensar en su soledad

**Comment by jxzerdz** [comment]
que vaya por unas kawazakis, digo, que vaya a ejercitarse para no pensar en su soledad
